### ISSUE TITLE
TypeError: Cannot read property 'privateKeys' of undefined

### ISSUE THREAD

**Issue by mvshvets** [TRON-US/docker-tron-quickstart#32]
Run trontools/quickstart:
```
docker run -it \
  -p 9090:9090 \
  --rm \
  --name tron \
  -d \
  trontools/quickstart
```

<img width="772" alt="image" src="https://user-images.githubusercontent.com/46225129/179411224-c76bad87-8860-490e-806c-782a145d2d86.png">

Run curl:
```
>> curl http://127.0.0.1:9090/admin/accounts
curl: (52) Empty reply from server
```

Docker-desktop console:
```
ADMIN /admin/accounts
(node:101) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'privateKeys' of undefined
    at flatAccounts (/tron/app/src/routes/admin.js:15:37)
    at getBalances (/tron/app/src/routes/admin.js:27:21)
    at /tron/app/src/routes/admin.js:127:26
    at Layer.handle [as handle_request] (/tron/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/tron/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/tron/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/tron/app/node_modules/express/lib/router/layer.js:95:5)
    at /tron/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/tron/app/node_modules/express/lib/router/index.js:335:12)
    at next (/tron/app/node_modules/express/lib/router/index.js:275:10)
```

**Comment by DanielG-2** [comment]
I've got the same issue. I even tried to request `/admin/accounts-generation` but I got into an endless loop of this:
`Sleeping for 1 second... Slept.
Sleeping for 1 second... Slept.
Sleeping for 1 second... Slept.
Sleeping for 1 second... Slept.
Sleeping for 1 second...(163) Waiting for sync...
`
