### ISSUE TITLE
Constant sleep loop on generate accounts

### ISSUE THREAD

**Issue by DamianRavi** [TRON-US/docker-tron-quickstart#4]
I've tried on a few different setups and it either sleeps constantly or gives this error:

> ADMIN /admin/accounts
(node:57) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pri                                                                                                             vateKeys' of undefined
    at flatAccounts (/tron/app/src/routes/admin.js:15:37)
    at getBalances (/tron/app/src/routes/admin.js:27:21)
    at /tron/app/src/routes/admin.js:127:26
    at Layer.handle [as handle_request] (/tron/app/node_modules/express/lib/rout                                                                                                             er/layer.js:95:5)
    at next (/tron/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/tron/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/tron/app/node_modules/express/lib/rout                                                                                                             er/layer.js:95:5)
    at /tron/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/tron/app/node_modules/express/lib/router/index.                                                                                                             js:335:12)
    at next (/tron/app/node_modules/express/lib/router/index.js:275:10)
(node:57) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This er                                                                                                             ror originated either by throwing inside of an async function without a catch bl                                                                                                             ock, or by rejecting a promise which was not handled with .catch(). (rejection i                                                                                                             d: 2)
(node:57) [DEP0018] DeprecationWarning: Unhandled promise rejections are depreca                                                                                                             ted. In the future, promise rejections that are not handled will terminate the N                                                                                                             ode.js process with a non-zero exit code.

**Comment by sullof** [comment]
That happens on some computers. It is caused by performance issues. It is not fixable because the code is correct and the performance issue is in javatron, which is just installed as is (we don't modify the javatron code, we just put all together).

**Comment by sullof** [comment]
I replicated the issue. I will try to fix it. Thanks.

**Comment by ceto-code** [comment]
Any updates on this?
